### ISSUE TITLE
how to run tests

### ISSUE THREAD

**Issue by ethers** [pipermerriam/ethereum-alarm-clock#41]
Congratulations on launching!
any tips on how to run tests?
Even with `pip install populus` I get this error in the alarmclock directory:

```
populus test
usage: populus [options] [file_or_dir] [file_or_dir] [...]
populus: error: unrecognized arguments: --ipdb
```

**Comment by pipermerriam** [comment]
This is due to the `pytest.ini` config.  If you just remove the `addopts= -s --ipdb` line then this error should subside.

Just an FYI.  This repo is not really ready for public consumption so use it knowing that there are likely more errors like this waiting for you.  Also be warned that you may need to *warm* up the `default-test` chain manually since DAG generation takes a while and currently populus doesn't handle this nicely and thinks that geth is just failing to start.

Feel free to keep posting any errors you get though.  Closing this issue.  Please re-open if the suggested fix doesn't work.

**Comment by ethers** [comment]
thanks :)

**Comment by ethers** [comment]
looks like this repo is ready now?  but no info on running tests...

**Comment by pipermerriam** [comment]
Instructions can now be found in the readme.  Thanks for the reminder.
