### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by EliezerIsrael** [pipermerriam/ethereum-alarm-clock#81]
Is this project still alive and well?

**Comment by pipermerriam** [comment]
My delay in responding to this may be more of a clue than anything.

My focus is currently elsewhere and while there are live contracts on the mainnet that are fully functional, the service is largely dormant.

I'm no longer running my execution servers so I suspect any scheduled calls will not end up being executed unless there is some other benevolent soul running execution servers.

I say *dormant* because I have every intention of rebooting the service, it's just a lower priority than the other work on my plate right now.
